Laboratorio 2

1. Inner-join

```{r}
library(nycflights13)
library(tidyverse)

flights
planes

#1.1
flights %>%
  inner_join(planes, by="tailnum")

#1.2
flights %>%
  inner_join(airlines, by="carrier")

#1.4
flights %>%
  inner_join(weather, by=c("year","month","day","hour","origin"))

#1.3
flights %>%
  inner_join(airports, by=c("dest"="faa"))

flights %>%
  inner_join(airports, by=c("origin"= "faa"))
```
2. Data manipulation

```{r}
flights %>%
  count(year, month, day) %>%
  filter(n > 1000) %>%
  arrange(n)
```
```{r}
flights_selected <- flights %>%
  select(hour, origin, dest, tailnum, carrier, arr_delay, dep_delay, year:day)

flights_selected  
```
2.3 left_join

```{r}
airlines %>%
  left_join(flights_selected, by="carrier") %>%
  select(-origin, -dest) %>%
  mutate(tot_delay = arr_delay+dep_delay)
```
2.4 flights_weather

```{r}
precip_delay <- flights %>%
  inner_join(weather, by=c("year","month","day","hour","origin")) %>%
  group_by(precip) %>%
  summarize(delay=mean(dep_delay,na.rm = TRUE)) %>%
  replace_na(list(delay=0))

precip_delay
```
2.5 ggplot

```{r}
ggplot(precip_delay, aes(x=precip, y=delay))+
  geom_point()
```
2.6

```{r}
flights_delay <- flights %>%
  filter(year==2013, month==5, day==10) %>%
  group_by(dest) %>%
  summarize(delay=mean(arr_delay, na.rm=TRUE))

flights_airports <- flights_delay %>%
  inner_join(airports, by=c("dest"="faa"))
flights_airports  
```
2.7 ggplot flights_airports

```{r}
ggplot(flights_airports, aes(x=lon, y=lat, color=delay, size=delay))+
  geom_point()
```
2.8

```{r}
flights %>%
  inner_join(planes, by="tailnum", suffix = c("_flights", "_planes")) %>%
  transmute(tailnum, manufacturer, pi=(dep_delay+arr_delay)/air_time)
  
```

